server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: document-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/document_db
      auditing:
        enabled: true
      connection-pool:
        max-size: 50
        min-size: 5