version: "3.8"
services:
  collabify-backend:
    depends_on: 
      - collabify-mongodb
      - collabify-redis
    image: "ghcr.io/tomerazuz/collabify-backend:latest"
    container_name: "collabify-backend"
    ports:
    - 9000:9000
    - 8000:8000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - MONGODB_URI=mongodb://localhost:27017/document_db

  collabify-ui:
    image: "ghcr.io/tomerazuz/collabify-ui:latest"
    container_name: "collabify-ui"
    ports:
    - 9001:9001
    environment:
      - PORT=9001
  
  collabify-redis:
    image: redis:latest
    container_name: "collabify-redis"
    ports:
      - 6379:6379

  collabify-mongodb:
    image: mongo:latest  
    container_name: "collabify-mongodb"
    ports:
      - 27017:27017 
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    