server:
  port: 9000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: document-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  config:
    import: optional:file:src/main/resources/.env[.properties]
  data:
    mongodb:
      uri: mongodb://localhost:27017/document_db
      auditing:
        enabled: true
      connection-pool:
        max-size: 50
        min-size: 5
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

firebase:
  config:
    path: "classpath:serviceAccountKey.json"