server:
  port: 9000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: document-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  config:
    import: optional:file:src/main/resources/.env[.properties]
  data:
    mongodb:
      auditing:
        enabled: true
      connection-pool:
        max-size: 50
        min-size: 5
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
  management:
    endpoints:
      web:
        exposure:
          include: health
firebase:
  config:
    path: "classpath:serviceAccountKey.json"

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: "mongodb://localhost:27017/${MONGO_DB_NAME}"

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: "mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.g35gc7t.mongodb.net/${MONGO_DB_NAME}?retryWrites=true&w=majority&appName=Cluster0"