server:
  port: 9000
  url: "https://collabify-app-72770cdb7df0.herokuapp.com"
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: document-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  config:
    import: optional:file:src/main/resources/.env[.properties]
  data:
    mongodb:
      uri: "mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.g35gc7t.mongodb.net/${MONGO_DB_NAME}?retryWrites=true&w=majority&appName=Cluster0"
      auditing:
        enabled: true
      connection-pool:
        max-size: 50
        min-size: 5
      ssl:
        enabled: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
  management:
    endpoints:
      web:
        exposure:
          include: health

liveblocks:
  key: ${LIVEBLOCKS_KEY_PROD}